name: notes_app_flutter
description: Aplicacion de resgistros de notas.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.1
  provider: ^6.0.5
  sqflite: ^2.2.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

